on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n spangnetes -g spangnetes9b7d-rg --location "East US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n spangnetes --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n spangnetes --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n spangnetes --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: spangnetes.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t spangnetes.azurecr.io/spangnetes:${{ github.sha }}
        docker push spangnetes.azurecr.io/spangnetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_spangnetes_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep spangnetesb189 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace spangnetesb189`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: spangnetesb189
        container-registry-url: spangnetes.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: spangnetesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: spangnetesb189
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          spangnetes.azurecr.io/spangnetes:${{ github.sha }}
        imagepullsecrets: |
          spangnetesdockerauth